version: "3"
services:
  metrics-manager:
    build:
      context: .
      # ports:
      # - "8888:8888/udp"
      # - "172.25.224.71:50000:50000/tcp"
    image: metrics-manager:stable
    container_name: metrics-manager
    working_dir: /app
    restart: unless-stopped
    command: [ "python", "main.py" ]
    # user: "1001"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      - /etc/localtime:/etc/localtime:ro # sync timezone with host machine
    network_mode: "host"
