version: "3"
services:
  metrics-manager:
    build:
      context: .
    ports:
      - "50001:50000/tcp"
    image: metrics-manager:latest
    container_name: metrics-manager
    working_dir: /app
    restart: unless-stopped
    command: [ "python", "main.py" ]
    user: "1001"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      - /etc/localtime:/etc/localtime:ro # sync timezone with host machine
    networks:
      - metrics-network
      - mqtt5-network

networks:
  metrics-network:
    external: true
  mqtt5-network:
    external: true
