[processor]
update_interval = 1
input_buffer_length = 65_536
output_buffer_length = 65_536
batch_size = 1_000

[processor.prometheus]
enable_prometheus_server = true
prometheus_port = 8_000
update_interval = 60

[server]
input_buffer_length = 65_536
host = "gfyvrdatadash"
port = 50000

[html_scraper_agent]
scrape_address = "http://pzeroheaterblocks.gf.local/"
update_interval = 3

[node_network]
read_limit = 1_000 # Security feature

[node_network.server]
enable_prometheus_server = false
prometheus_port = 8_000
update_interval = 1

[node_network.client]
enable_prometheus_server = false
prometheus_port = 8_000
update_interval = 1
timeout = 5
