[processor]
update_interval = 0.5
input_buffer_length = 100_000
output_buffer_length = 100_000
batch_size = 2_000

[processor.prometheus]
enable_prometheus_server = true
prometheus_port = 8_000
update_interval = 10

[server]
input_buffer_length = 100_000
host = "gfyvrdatadash"
port = 50000

[html_scraper_agent]
scrape_address = "http://pzeroheaterblocks.gf.local/"
update_interval = 5

[node_network]
read_limit = 1_000 # Security feature

[node_network.server]
enable_prometheus_server = false
prometheus_port = 8_000
update_interval = 1

[node_network.client]
enable_prometheus_server = false
prometheus_port = 8_000
update_interval = 1
timeout = 3
