secrets_filepath = ".env"

[processor]
update_interval = 0.5
input_buffer_length = 100_000
output_buffer_length = 100_000
batch_size = 2_000

[processor.prometheus]
enable_prometheus_server = true
prometheus_port = 8_000
update_interval = 10

[database_client]
config_file = "config/.influx_test.toml"

[server]
input_buffer_length = 100_000
host = "gfyvrdatadash"
port = 50000

[html_scraper_agent]
scrape_address = "http://pzeroheaterblocks.gf.local/"
update_interval = 10

[node_network]
read_limit = 1_000 # Security feature

[node_network.server]
enable_prometheus_server = false
prometheus_port = 8_000
update_interval = 1

[node_network.client]
enable_prometheus_server = false
prometheus_port = 8_000
update_interval = 1
timeout = 3

[mqtt.client]
name = "mqtt-client-metrics-manager-latest"
node_id = "metrics_manager_pzero"
subscribe_topics = ["prototype-zero/#"]
subscribe_qos = 0

[mqtt.broker]
# hostname = "gfyvrdatadash"
hostname = "emqx-broker"
port = 1_883
timeout = 5

[mqtt.node_network]
topic_structure = "machine/module/measurement/field*"
enable_prometheus_server = false
prometheus_port = 8_000
