version: 1

handlers:
  console:
    class : logging.StreamHandler
    formatter: default
    level   : INFO
    stream  : ext://sys.stdout
  metrics_manager.debug.file:
    class : logging.handlers.RotatingFileHandler
    formatter: json
    level   : DEBUG
    filename: logs/metrics_manager.debug.log
    maxBytes: 1_000_000
    backupCount: 3
  metrics_processor.debug.file:
    class : logging.handlers.RotatingFileHandler
    formatter: json
    level   : DEBUG
    filename: logs/metrics_processor.debug.log
    maxBytes: 1_000_000
    backupCount: 3
  metrics_manager.info.file:
    class : logging.handlers.RotatingFileHandler
    formatter: json
    level   : INFO
    filename: logs/metrics_manager.info.log
    maxBytes: 1_000_000
    backupCount: 3
  scraper_agent.debug.file:
    class : logging.handlers.RotatingFileHandler
    formatter: json
    level   : DEBUG
    filename: logs/scraper_agent.debug.log
    maxBytes: 1_000_000
    backupCount: 3
  node_network.debug.file:
    class : logging.handlers.RotatingFileHandler
    formatter: json
    level   : DEBUG
    filename: logs/node_network.debug.log
    maxBytes: 1_000_000
    backupCount: 3
  node_network.info.file:
    class : logging.handlers.RotatingFileHandler
    formatter: json
    level   : INFO
    filename: logs/node_network.info.log
    maxBytes: 1_000_000
    backupCount: 3

formatters:
  brief:
    format: '%(message)s'
  default:
    format: '%(asctime)s %(levelname)-8s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  verbose:
    format: "%(asctime)s,%(msecs)d - %(name)s - %(levelname)-8s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(levelname)s %(message)s'

loggers:
  metrics_manager:
    level: DEBUG
    handlers:
      - console
      - metrics_manager.info.file
      - metrics_manager.debug.file

  metrics_processor:
    level: DEBUG
    handlers:
      - metrics_manager.info.file
      - metrics_processor.debug.file

  html_scraper_agent:
    level: DEBUG
    handlers:
      - metrics_manager.info.file
      - scraper_agent.debug.file

  data_node_network:
    level: DEBUG
    handlers:
      - metrics_manager.info.file
      - node_network.debug.file
      - node_network.info.file
  
  # fast_database_clients.fast_influxdb_client.influx_client:
  #   level: DEBUG
  #   handlers:
  #     - metrics_manager.debug.file
  #     - metrics_manager.info.file