top_PID:
  data_type: float
  tags:
    type_measure: setpoint
    type_hardware: heater power
    location: upper
  
bot_PID:
  data_type: float
  tags:
    type_measure: setpoint
    type_hardware: heater power
    location: upper
  
top_batterylevel:
  data_type: float
  tags:
    type_measure: percentage
    type_hardware: battery
    location: upper
  
bot_batterylevel:
  data_type: float
  tags:
    type_measure: percentage
    type_hardware: battery
    location: lower
  
top_TC1:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: thermocouple
    location: upper, position 1
  
top_TC2:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: thermocouple
    location: upper, position 2
  
top_TC3:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: thermocouple
    location: upper, position 3

top_TC4:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: thermocouple
    location: upper, position 4
  
bot_TC1:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: thermocouple
    location: lower, position 1  
  
bot_TC2:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: thermocouple
    location: lower, position 2  
  
bot_TC3:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: thermocouple
    location: lower, position 3  

bot_TC4:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: thermocouple
    location: lower, position 4 
  
IR_ref:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: thermocouple
    location: internal to IR sensor
  
IR_array_temp0:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: infrared
    location: liner bottom +0
  
IR_array_temp1:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: infrared
    location: liner bottom +1  
  
IR_array_temp2:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: infrared
    location: liner bottom +2
  
IR_array_temp3:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: infrared
    location: liner bottom +3
  
IR_array_temp4:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: infrared
    location: liner bottom +4
  
IR_array_temp5:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: infrared
    location: liner bottom +5  
  
IR_array_temp6:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: infrared
    location: liner bottom +6
  
IR_array_temp7:
  data_type: float
  tags:
    type_measure: temperature
    type_hardware: infrared
    location: liner bottom +7
  
top_setpoint:
  data_type: float
  tags:
    type_measure: setpoint
    location: upper
  
bot_setpoint:
  data_type: float
  tags:
    type_measure: setpoint
    location: lower
  
upper_pressure:
  data_type: float
  source_id: upper_pressure
  tags:
    type_measure: pressure
    type_hardware: stinger
    location: upper

lower_pressure:
  data_type: float
  tags:
    type_measure: pressure
    type_hardware: stinger
    location: lower
  
upper_pressure_voltage:
  data_type: float
  source_id: upper_pressure_voltage
  tags:
    type_measure: pressure
    type_hardware: stinger
    location: upper

lower_pressure_voltage:
  data_type: float
  tags:
    type_measure: pressure
    type_hardware: stinger
    location: lower

SD_card_status:
  data_type: string
  tags:
    type_measure: status
    type_hardware: SD card
  
logging_status:
  data_type: string
  tags:
    type_measure: status
    type_hardware: SD card
  
top_batwarning:
  data_type: string
  tags:
    type_measure: status
    type_hardware: battery
  
bot_batwarning:
  data_type: string
  tags:
    type_measure: status
    type_hardware: battery
  
upper_pressure_gastype:
  data_type: string
  source_id: gas
  tags:
    type_measure: gas type
    type_hardware: pressure gauge
    location: upper

top_timestamp:
  data_type: string
  tags:
    type_measure: time

bot_timestamp:
  data_type: string
  tags:
    type_measure: time