[TimeLocalizer]
local_tz = "America/Vancouver"
offset = [1, 0, 0]             # offset to time in [hours, minutes, seconds]

[ExtraTagger]
campaign = "Commissioning"
testbed = "PZero"

[Formatter]
formats_filepath = "config/metric_format.yaml"

[OutlierRemover]
boundaries_filepath = "config/metric_boundaries.yaml"

[PropertyMapper]
property_mapping_filepath = "config/property_mapping.yaml"

[BinaryOperations]
binary_operations_filepath = "config/binary_operations.yaml"

[PropertyConstructor]
property_group = "tags"
property_recipes = { id = "measurement/field" } # Note: Use 'field' to specify first item of the 'fields' property
