# field: database_name
fields:
  IR_Ref: IR1_ref
  IR_0: IR1_array_temp0
  IR_1: IR1_array_temp1
  IR_2: IR1_array_temp2
  IR_3: IR1_array_temp3
  IR_4: IR1_array_temp4
  IR_5: IR1_array_temp5
  IR_6: IR1_array_temp6
  IR_7: IR1_array_temp7
  IR2_Ref: IR2_ref
  IR2_0: IR2_array_temp0
  IR2_1: IR2_array_temp1
  IR2_2: IR2_array_temp2
  IR2_3: IR2_array_temp3
  IR2_4: IR2_array_temp4
  IR2_5: IR2_array_temp5
  IR2_6: IR2_array_temp6
  IR2_7: IR2_array_temp7
  upper_pressure: upper_pressure_N2
  lower_pressure: lower_pressure_N2
  gas: upper_pressure_gastype
  IR_ref: IR1_ref
  IR_array_temp0: IR1_array_temp0 
  IR_array_temp1: IR1_array_temp1 
  IR_array_temp2: IR1_array_temp2 
  IR_array_temp3: IR1_array_temp3 
  IR_array_temp4: IR1_array_temp4 
  IR_array_temp5: IR1_array_temp5 
  IR_array_temp6: IR1_array_temp6 
  IR_array_temp7: IR1_array_temp7 

# measurement:
#   cartridge_pressure: liner_heater