top_timestamp:
  - top_PID
  - top_batterylevel
  - top_TC1
  - top_TC2
  - top_TC3
  - IR_ref
  - IR_array_temp0
  - IR_array_temp1
  - IR_array_temp2
  - IR_array_temp3
  - IR_array_temp4
  - IR_array_temp5
  - IR_array_temp6
  - IR_array_temp7
  - top_setpoint
  - upper_pressure
  - upper_pressure_voltage
  - gas

bot_timestamp:
  - bot_PID
  - bot_batterylevel
  - bot_TC1
  - bot_TC2
  - bot_TC3
  - bot_setpoint
  - lower_pressure
  - lower_pressure_voltage

no_timestamp:
  - SD_card_status
  - logging_status
  - top_batwarning
  - bot_batwarning